#!/bin/bash
#
# Script to update console related tests from source
#

for i in sc illegal decrementer xics privileged mmu misc modes reservation trace fpu ; do
    cd $i
    make
    cd -
    cp $i/$i.bin test_$i.bin
    ln -s test_$i.bin main_ram.bin
    ../core_tb > /dev/null 2> test_$i.console_out
    rm main_ram.bin
done
